server:
  port: 8085

spring:
  application:
    name: profile-service
  datasource:
    url: jdbc:postgresql://techlinker.postgres.database.azure.com:5432/postgres
    username: admin32
    password: ad8m0in32#34
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/