server:
  port: 8092

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://config-service:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/developers/**,/api/v1/companies/**
        - id: employment-service
          uri: lb://employment-service
          predicates:
            - Path=/api/v1/posts/**
        - id: messaging-service
          uri: lb://messaging-service
          predicates:
            - Path=/api/v1/messages/**
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/v1/digital_profiles/**,/api/v1/educations/**,/api/v1/frameworks/**,/api/v1/projects/**,/api/v1/study-centers/**